name = "HaloArrays"
uuid = "fb8acbf3-7450-4a92-9b90-d90d6800475e"
version = "0.1.0"
authors = ["Davide Lasagna <davide.lasagna@soton.ac.uk>", "Thomas Burton <tburton5572@gmail.com>"]

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
MPI = "0.20.23"
